# Generated by Django 4.0.6 on 2022-08-23 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_room_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='fav_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
